[theme]
primaryColor = "#000000ff"
backgroundColor = "#e1cf00ff"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" # Default


[[theme.fontFaces]]
fontFamily = "Times New Roman"
src = ["url(times_new_roman.ttf) format('truetype')"]